files:
    include: '**/*.s+(a|c)ss'
    ignore:
        - 'src/styles/vendor/**/*.*'
        - 'node_modules/**/*.*'
rules:
    indentation:
        - 1
        -
            size: 4
    empty-line-between-blocks:
        - 1
        -
            include: false
    nesting-depth:
        - 1
        -
            max-depth: 4
    leading-zero:
        - 1
        -
            include: true
    property-sort-order:
        - 1
        -
            order: smacss
    no-important:
        - 0
    no-qualifying-elements:
        - 0
    force-element-nesting:
        - 0
    force-attribute-nesting:
        - 0
    force-pseudo-nesting:
        - 0
    class-name-format:
        - 0
    no-transition-all:
        - 0
    placeholder-in-extend:
        - 0
