language: node_js
cache:
  yarn: true
script:
- bin/run_build.sh
- bin/run_test.sh
- bin/run_lint.sh
before_install:
  - yarn global add gulp codecov sass-lint
branches:
  only:
  - master
  - staging
env:
    matrix:
      - RUN_LINT=true RUN_TEST=true
      - RUN_BUILD=true
before_deploy:
  - pip install --user awscli
deploy:
- provider: script
  script: ~/.local/bin/aws s3 sync public s3://cru-mpdx-web-stage --region us-east-1 --acl public-read --exclude '*.html' --cache-control 'public, max-age=31536000' --delete
  skip_cleanup: true
  on:
    branch: staging
    condition: '"$RUN_BUILD" = "true"'
- provider: script
  script: ~/.local/bin/aws s3 sync public s3://cru-mpdx-web-stage --region us-east-1 --acl public-read --include '*.html' --cache-control 'public, no-cache' --delete
  skip_cleanup: true
  on:
    branch: staging
    condition: '"$RUN_BUILD" = "true"'
- provider: script
  script: ~/.local/bin/aws s3 sync public s3://cru-mpdx-web-prod --region us-east-1 --acl public-read --exclude '*.html' --cache-control 'public, max-age=31536000'
  skip_cleanup: true
  on:
    branch: master
    condition: '"$RUN_BUILD" = "true"'
- provider: script
  script: ~/.local/bin/aws s3 sync public s3://cru-mpdx-web-prod --region us-east-1 --acl public-read --include '*.html' --cache-control 'public, no-cache'
  skip_cleanup: true
  on:
    branch: master
    condition: '"$RUN_BUILD" = "true"'
